/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterIndexRouteImport } from './routes/master.index'
import { Route as MasterTenantsRouteImport } from './routes/master.tenants'
import { Route as MasterOrdersRouteImport } from './routes/master.orders'
import { Route as MasterLoginRouteImport } from './routes/master.login'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as AppSlugOrdersRouteImport } from './routes/app.$slug.orders'
import { Route as AppSlugLoginRouteImport } from './routes/app.$slug.login'
import { Route as AppSlugDashboardRouteImport } from './routes/app.$slug.dashboard'
import { Route as ApiPublicWebhookGatewayRouteImport } from './routes/api/public/webhook.$gateway'
import { Route as ApiPublicHooksTickOrdersRouteImport } from './routes/api/public/hooks/tick-orders'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterTenantsRoute = MasterTenantsRouteImport.update({
  id: '/master/tenants',
  path: '/master/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterOrdersRoute = MasterOrdersRouteImport.update({
  id: '/master/orders',
  path: '/master/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLoginRoute = MasterLoginRouteImport.update({
  id: '/master/login',
  path: '/master/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugOrdersRoute = AppSlugOrdersRouteImport.update({
  id: '/app/$slug/orders',
  path: '/app/$slug/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugLoginRoute = AppSlugLoginRouteImport.update({
  id: '/app/$slug/login',
  path: '/app/$slug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugDashboardRoute = AppSlugDashboardRouteImport.update({
  id: '/app/$slug/dashboard',
  path: '/app/$slug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookGatewayRoute = ApiPublicWebhookGatewayRouteImport.update({
  id: '/api/public/webhook/$gateway',
  path: '/api/public/webhook/$gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickOrdersRoute =
  ApiPublicHooksTickOrdersRouteImport.update({
    id: '/api/public/hooks/tick-orders',
    path: '/api/public/hooks/tick-orders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/master/login': typeof MasterLoginRoute
  '/master/orders': typeof MasterOrdersRoute
  '/master/tenants': typeof MasterTenantsRoute
  '/master/': typeof MasterIndexRoute
  '/app/$slug/dashboard': typeof AppSlugDashboardRoute
  '/app/$slug/login': typeof AppSlugLoginRoute
  '/app/$slug/orders': typeof AppSlugOrdersRoute
  '/api/public/hooks/tick-orders': typeof ApiPublicHooksTickOrdersRoute
  '/api/public/webhook/$gateway': typeof ApiPublicWebhookGatewayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/master/login': typeof MasterLoginRoute
  '/master/orders': typeof MasterOrdersRoute
  '/master/tenants': typeof MasterTenantsRoute
  '/master': typeof MasterIndexRoute
  '/app/$slug/dashboard': typeof AppSlugDashboardRoute
  '/app/$slug/login': typeof AppSlugLoginRoute
  '/app/$slug/orders': typeof AppSlugOrdersRoute
  '/api/public/hooks/tick-orders': typeof ApiPublicHooksTickOrdersRoute
  '/api/public/webhook/$gateway': typeof ApiPublicWebhookGatewayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/master/login': typeof MasterLoginRoute
  '/master/orders': typeof MasterOrdersRoute
  '/master/tenants': typeof MasterTenantsRoute
  '/master/': typeof MasterIndexRoute
  '/app/$slug/dashboard': typeof AppSlugDashboardRoute
  '/app/$slug/login': typeof AppSlugLoginRoute
  '/app/$slug/orders': typeof AppSlugOrdersRoute
  '/api/public/hooks/tick-orders': typeof ApiPublicHooksTickOrdersRoute
  '/api/public/webhook/$gateway': typeof ApiPublicWebhookGatewayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/sitemap.xml'
    | '/loja/$slug'
    | '/master/login'
    | '/master/orders'
    | '/master/tenants'
    | '/master/'
    | '/app/$slug/dashboard'
    | '/app/$slug/login'
    | '/app/$slug/orders'
    | '/api/public/hooks/tick-orders'
    | '/api/public/webhook/$gateway'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/sitemap.xml'
    | '/loja/$slug'
    | '/master/login'
    | '/master/orders'
    | '/master/tenants'
    | '/master'
    | '/app/$slug/dashboard'
    | '/app/$slug/login'
    | '/app/$slug/orders'
    | '/api/public/hooks/tick-orders'
    | '/api/public/webhook/$gateway'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/sitemap.xml'
    | '/loja/$slug'
    | '/master/login'
    | '/master/orders'
    | '/master/tenants'
    | '/master/'
    | '/app/$slug/dashboard'
    | '/app/$slug/login'
    | '/app/$slug/orders'
    | '/api/public/hooks/tick-orders'
    | '/api/public/webhook/$gateway'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LojaSlugRoute: typeof LojaSlugRoute
  MasterLoginRoute: typeof MasterLoginRoute
  MasterOrdersRoute: typeof MasterOrdersRoute
  MasterTenantsRoute: typeof MasterTenantsRoute
  MasterIndexRoute: typeof MasterIndexRoute
  AppSlugDashboardRoute: typeof AppSlugDashboardRoute
  AppSlugLoginRoute: typeof AppSlugLoginRoute
  AppSlugOrdersRoute: typeof AppSlugOrdersRoute
  ApiPublicHooksTickOrdersRoute: typeof ApiPublicHooksTickOrdersRoute
  ApiPublicWebhookGatewayRoute: typeof ApiPublicWebhookGatewayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/tenants': {
      id: '/master/tenants'
      path: '/master/tenants'
      fullPath: '/master/tenants'
      preLoaderRoute: typeof MasterTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/orders': {
      id: '/master/orders'
      path: '/master/orders'
      fullPath: '/master/orders'
      preLoaderRoute: typeof MasterOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/login': {
      id: '/master/login'
      path: '/master/login'
      fullPath: '/master/login'
      preLoaderRoute: typeof MasterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug/orders': {
      id: '/app/$slug/orders'
      path: '/app/$slug/orders'
      fullPath: '/app/$slug/orders'
      preLoaderRoute: typeof AppSlugOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug/login': {
      id: '/app/$slug/login'
      path: '/app/$slug/login'
      fullPath: '/app/$slug/login'
      preLoaderRoute: typeof AppSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug/dashboard': {
      id: '/app/$slug/dashboard'
      path: '/app/$slug/dashboard'
      fullPath: '/app/$slug/dashboard'
      preLoaderRoute: typeof AppSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/$gateway': {
      id: '/api/public/webhook/$gateway'
      path: '/api/public/webhook/$gateway'
      fullPath: '/api/public/webhook/$gateway'
      preLoaderRoute: typeof ApiPublicWebhookGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-orders': {
      id: '/api/public/hooks/tick-orders'
      path: '/api/public/hooks/tick-orders'
      fullPath: '/api/public/hooks/tick-orders'
      preLoaderRoute: typeof ApiPublicHooksTickOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LojaSlugRoute: LojaSlugRoute,
  MasterLoginRoute: MasterLoginRoute,
  MasterOrdersRoute: MasterOrdersRoute,
  MasterTenantsRoute: MasterTenantsRoute,
  MasterIndexRoute: MasterIndexRoute,
  AppSlugDashboardRoute: AppSlugDashboardRoute,
  AppSlugLoginRoute: AppSlugLoginRoute,
  AppSlugOrdersRoute: AppSlugOrdersRoute,
  ApiPublicHooksTickOrdersRoute: ApiPublicHooksTickOrdersRoute,
  ApiPublicWebhookGatewayRoute: ApiPublicWebhookGatewayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
