/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoTokenRouteImport } from './routes/pedido.$token'
import { Route as ApiPublicWebhookGatewayRouteImport } from './routes/api/public/webhook.$gateway'
import { Route as ApiPublicHooksTickOrdersRouteImport } from './routes/api/public/hooks/tick-orders'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoTokenRoute = PedidoTokenRouteImport.update({
  id: '/pedido/$token',
  path: '/pedido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookGatewayRoute = ApiPublicWebhookGatewayRouteImport.update({
  id: '/api/public/webhook/$gateway',
  path: '/api/public/webhook/$gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickOrdersRoute =
  ApiPublicHooksTickOrdersRouteImport.update({
    id: '/api/public/hooks/tick-orders',
    path: '/api/public/hooks/tick-orders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/api/public/hooks/tick-orders': typeof ApiPublicHooksTickOrdersRoute
  '/api/public/webhook/$gateway': typeof ApiPublicWebhookGatewayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/api/public/hooks/tick-orders': typeof ApiPublicHooksTickOrdersRoute
  '/api/public/webhook/$gateway': typeof ApiPublicWebhookGatewayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/api/public/hooks/tick-orders': typeof ApiPublicHooksTickOrdersRoute
  '/api/public/webhook/$gateway': typeof ApiPublicWebhookGatewayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/sitemap.xml'
    | '/pedido/$token'
    | '/api/public/hooks/tick-orders'
    | '/api/public/webhook/$gateway'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/sitemap.xml'
    | '/pedido/$token'
    | '/api/public/hooks/tick-orders'
    | '/api/public/webhook/$gateway'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/sitemap.xml'
    | '/pedido/$token'
    | '/api/public/hooks/tick-orders'
    | '/api/public/webhook/$gateway'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PedidoTokenRoute: typeof PedidoTokenRoute
  ApiPublicHooksTickOrdersRoute: typeof ApiPublicHooksTickOrdersRoute
  ApiPublicWebhookGatewayRoute: typeof ApiPublicWebhookGatewayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$token': {
      id: '/pedido/$token'
      path: '/pedido/$token'
      fullPath: '/pedido/$token'
      preLoaderRoute: typeof PedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/$gateway': {
      id: '/api/public/webhook/$gateway'
      path: '/api/public/webhook/$gateway'
      fullPath: '/api/public/webhook/$gateway'
      preLoaderRoute: typeof ApiPublicWebhookGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-orders': {
      id: '/api/public/hooks/tick-orders'
      path: '/api/public/hooks/tick-orders'
      fullPath: '/api/public/hooks/tick-orders'
      preLoaderRoute: typeof ApiPublicHooksTickOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PedidoTokenRoute: PedidoTokenRoute,
  ApiPublicHooksTickOrdersRoute: ApiPublicHooksTickOrdersRoute,
  ApiPublicWebhookGatewayRoute: ApiPublicWebhookGatewayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
